# for MoveIt controller list
controller_list:
  - name: dualarm/mani1_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mani1_joint1
      - mani1_joint2
      - mani1_joint3
      - mani1_joint4
      - mani1_joint5
      - mani1_joint6
      - mani1_joint7

    pid_gains:
      mani1_joint1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint6: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani1_joint7: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  - name: dualarm/mani2_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mani2_joint1
      - mani2_joint2
      - mani2_joint3
      - mani2_joint4
      - mani2_joint5
      - mani2_joint6
      - mani2_joint7

    pid_gains:
      mani2_joint1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint6: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      mani2_joint7: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  - name: dualarm/body_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - dummy_joint
      - dummy_joint_1
      - dummy_joint_2

    pid_gains:
      dummy_joint  : {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      dummy_joint_1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      dummy_joint_2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}

#
#  - name: manipulator1_torque
#    action_ns: dualarm_config
#    type: FollowJointTrajectory
#    joints:
#      - mani1_joint1
#      - mani1_joint2
#      - mani1_joint3
#      - mani1_joint4
#      - mani1_joint5
#      - mani1_joint6
#      - mani1_joint7
#    pid_gains:
#      mani1_joint1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani1_joint2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani1_joint3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani1_joint4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani1_joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani1_joint6: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani1_joint7: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#
#  - name: manipulator2_torque
#    action_ns: dualarm_config
#    type: FollowJointTrajectory
#    joints:
#    - mani2_joint1
#    - mani2_joint2
#    - mani2_joint3
#    - mani2_joint4
#    - mani2_joint5
#    - mani2_joint6
#    - mani2_joint7
#    pid_gains:
#      mani2_joint1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani2_joint2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani2_joint3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani2_joint4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani2_joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani2_joint6: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
#      mani2_joint7: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
