controller_list:
  - name: mani1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - mani1_joint1
      - mani1_joint2
      - mani1_joint3
      - mani1_joint4
      - mani1_joint5
      - mani1_joint6
      - mani1_joint7
  - name: mani2_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - mani2_joint1
      - mani2_joint2
      - mani2_joint3
      - mani2_joint4
      - mani2_joint5
      - mani2_joint6
      - mani2_joint7
  - name: body_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - dummy_joint